#!/bin/bash

script_path="$HOME/scripts"
script_file="$script_path/$1"
script_editor="vim"

if [[ -f $script_file ]]; then
    eval $script_editor $script_file
else
    echo '#!/usr/bin/env bash' > $script_file
    chmod +x $script_file
    eval $script_editor $script_file
fi

