#!/usr/bin/env bash

# Your favorite editor...
script_editor="vim"
# Default destination of your scripts...
script_path="$HOME/scripts"

# Script file name...
script_file="$script_path/$1"

if [[ ! -f $script_file ]]; then
    echo -e "#!/usr/bin/env bash\n\n" > $script_file
    chmod u+x $script_file
fi

eval $script_editor $script_file
