#!/usr/bin/env bash

# important! requires 'ssgen' script

script_path="$HOME/.local/bin"
ssgen_path="$script_path"

# dmenu theming
prompt="ssgen: "
lines="30"
font="Monaco-11"
colors="-nb #2C323E -nf #9899a0 -sb #81A1C1 -sf #E5E9F0"

# list only executable non-binay files

list="$(find $script_path -maxdepth 1 -type f -executable \
       -exec grep -Iq . {} \; -print \
       | sed 's|^'$script_path/'||' \
       | sort \
       )"

# output list to dmenu

select="$(dmenu -p $prompt -fn "$font" $colors -l $lines <<< $list)"

# run 'ssgen' with the selected file name

if [[ ! -z "$select" ]]; then
    eval "$ssgen_path/ssgen $select"
fi

exit 0;
